# Generated by Django 3.1 on 2020-08-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('termservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='description',
            field=models.TextField(default='default description', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='short_name',
            field=models.CharField(max_length=100, verbose_name='Короткое наименование'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала действия справочника текущей версии'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='version',
            field=models.CharField(max_length=20, unique=True, verbose_name='Версия справочника'),
        ),
        migrations.AlterField(
            model_name='item_directory',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Код элемента'),
        ),
        migrations.AlterField(
            model_name='item_directory',
            name='id_dir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='termservice.directory', verbose_name='Справочник'),
        ),
        migrations.AlterField(
            model_name='item_directory',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Значение элемента'),
        ),
    ]
