# Generated by Django 3.1 on 2020-08-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termservice', '0002_auto_20200818_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала действия справочника текущей версии'),
        ),
    ]
