# Generated by Django 3.1 on 2020-08-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termservice', '0003_auto_20200818_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='version',
            field=models.CharField(max_length=20, verbose_name='Версия справочника'),
        ),
        migrations.AddConstraint(
            model_name='directory',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_version'),
        ),
    ]
