# Generated by Django 3.1 on 2020-08-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termservice', '0004_auto_20200822_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
